name: Branch Deployments

on:
  pull_request:
    branches:
      - main  # Adjust this to your main branch

jobs:
  code-quality-and-static-analysis:
    name: Code Quality and Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
      - name: Checkout PyTorch
        uses: actions/checkout@master
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        uses: suo/flake8-github-action@releases/v1
        with:
          checkName: 'code-quality-and-static-analysis'   # NOTE: this needs to be the same as the job name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    needs:
      - code-quality-and-static-analysis
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Run unit tests
        run: echo "Running unit tests..."

  push_to_registry:
    name: Build and Push Docker image
    runs-on: ubuntu-latest
    needs:
      - code-quality-and-static-analysis
      - Unit-test
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: valentinofantini/scaffolding
      
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
    
  deploy-to-development:
    name: Deploy / Development
    runs-on: ubuntu-latest
    needs:
      - code-quality-and-static-analysis
      - push_to_registry
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Deploy to development
        run: echo "Deploying to development environment..."

